### ISSUE TITLE
Additional 2nd Factor Types?

### ISSUE THREAD

**Issue by luc-ass** [fschili/DicomLinkExchange#3]
**To Do:**
Research additional information, that is regularly used by portal systems to authenticate users.

**Reasoning:**
Typical authentication methods should be defined as standard. An example would be date as `YYYYMMDD`, not `MM-DD-YYYY` or other formats.

**Comment by fschili** [comment]
Im letzten Meeting des Arbeitskreis wurde beschlossen sich auf die 4 Typen: Birthdate, Studydate, Password und Custom zu reduzieren.

* `PAT_BIRTH_DATE` - e.g. date from dicom: Patient's Birth Date (0010,0030)
* `STUDY_DATE` - e.g. date from dicom: Study Date (0008,0020)
* `PASSWORD` - e.g. an OTP oder TOTP as string
* `CUSTOM` - any custom value which is not specified above
